variable "aws_region" {}
variable "vpc_cidr" {}
variable "pub_sub" {}
variable "priv_sub" {}
variable "ami_linux" {}
variable "ami_windows" {}
variable "instance_size" {}
variable "key_name" {}
variable "instance_count" {}
variable "lb_type" {}
